# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "kameronkenny.com"
email: "thiswillnotwork@thelinux.pro"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kameronkenny.com" # the base hostname & protocol for your site
twitter_username: kameronkenny
github_username:  kkenny
linkedin_username: kameronkenny

currently_reading_title: "The Captain Class"
currently_reading_author: "Sam Walker"
currently_reading_image: "https://books.google.com/books/content?id=pKD4DAAAQBAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE73Q5Qh8WByqrMkpgV4NydjjFJOBiu2ZBHQxeck_eir_ntGJgu1v6QsL5GDDfxoSGb4kxC1AD2Mul1vhITZ-VZc79SX7IW_OSF0ZRAizgTZhoD-gynzlFE24Dig7PJUbHERALEUI"


# Build settings
markdown: kramdown


theme: jekyll-theme-slate
